//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_vyw_resume_picture
    {
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<bool> isShow { get; set; }
        public string contactEmail { get; set; }
        public string address { get; set; }
        public string mobile { get; set; }
        public Nullable<int> workTime { get; set; }
        public Nullable<int> education { get; set; }
        public string birthday { get; set; }
        public Nullable<int> sex { get; set; }
        public Nullable<int> userID { get; set; }
        public string describe { get; set; }
        public string position { get; set; }
        public int pictureID { get; set; }
        public string realName { get; set; }
        public int resumeID { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public Nullable<int> typeID { get; set; }
        public Nullable<bool> isDelete { get; set; }
    }
}
