//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_vyw_active_user
    {
        public System.DateTime activeTime { get; set; }
        public string activeToken { get; set; }
        public int userID { get; set; }
        public int activeType { get; set; }
        public int activeID { get; set; }
        public Nullable<bool> bindStatus { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string nickName { get; set; }
    }
}
