//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_vyw_music_user
    {
        public int musicID { get; set; }
        public string musicName { get; set; }
        public string musicAuthor { get; set; }
        public string musicLink { get; set; }
        public Nullable<int> weight { get; set; }
        public int userID { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public string nickName { get; set; }
        public string email { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<int> hot { get; set; }
        public Nullable<bool> isRecommend { get; set; }
        public string coverImage { get; set; }
        public string username { get; set; }
    }
}
