//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_vyw_plan_content
    {
        public int hot { get; set; }
        public int weight { get; set; }
        public string content { get; set; }
        public int detailID { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public int planID { get; set; }
        public int userID { get; set; }
        public Nullable<bool> isRecommend { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<int> status { get; set; }
        public string tags { get; set; }
        public string describe { get; set; }
        public string title { get; set; }
        public string planTitle { get; set; }
    }
}
