//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_vyw_achievements_icon
    {
        public int achievementsID { get; set; }
        public string name { get; set; }
        public int count { get; set; }
        public int iconID { get; set; }
        public int userID { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public string title { get; set; }
        public string iconClass { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string nickName { get; set; }
        public Nullable<int> roleID { get; set; }
    }
}
