//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_qq_login
    {
        public int ID { get; set; }
        public Nullable<int> ret { get; set; }
        public string msg { get; set; }
        public string nickname { get; set; }
        public string figureurl { get; set; }
        public string figureurl_1 { get; set; }
        public string figureurl_2 { get; set; }
        public string figureurl_qq_1 { get; set; }
        public string figureurl_qq_2 { get; set; }
        public string gender { get; set; }
        public Nullable<int> is_yellow_vip { get; set; }
        public Nullable<int> vip { get; set; }
        public string yellow_vip_level { get; set; }
        public string level { get; set; }
        public Nullable<int> is_yellow_year_vip { get; set; }
        public string openid { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
    }
}
