//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_user
    {
        public int userID { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string nickName { get; set; }
        public Nullable<int> sex { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> pictureID { get; set; }
        public Nullable<bool> bindStatus { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<int> loginCount { get; set; }
        public string motto { get; set; }
        public string signature { get; set; }
        public int status { get; set; }
        public Nullable<int> qqID { get; set; }
        public Nullable<System.DateTime> signTime { get; set; }
        public Nullable<System.DateTime> loginTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    }
}
